branch-defaults:
  default:
    environment: null
global:
  application_name: udagram
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: EMR_EC2_DefaultRole
  repository: null
  sc: null
  workspace_type: Application
